### ISSUE TITLE
Не обновляется несколько крайних левых колонок 

### ISSUE THREAD

**Issue by alexey496** [nickit94/oled-ssd1306-sh1106-stm32-hal#1]
Здравствуйте! 
Спасибо за драйвер - это хорошая работа.
Я заметил один баг: при обновлении экрана несколько крайних левых столбцов не обновляются.
Я исправил это закомментировав следующее:
		OLED_SendCommand(0x00 /*| (oled_start_column & 0x0F)*/);	// lo tetrad starting column address
		OLED_SendCommand(0x10 /*| (oled_start_column >> 4)*/);		// hi tetrad starting column address
Не знаю, насколько это правильно, но это работает.

Полный листинг функции с закоментированными строками:

void OLED_UpdateScreen()
{
	for (uint8_t page_number = 0; page_number < 8; page_number++)
	{
		OLED_SendCommand(0x00 /*| (oled_start_column & 0x0F)*/);	// lo tetrad starting column address
		OLED_SendCommand(0x10 /*| (oled_start_column >> 4)*/);		// hi tetrad starting column address

		OLED_SendCommand(0xB0 | page_number);					// starting address of the page

		for (int16_t j = 0; j < OLED_WIDTH; j++)
		{
			OLED_SendData(oled_buffer[page_number * OLED_WIDTH + j]);
		}
	}
}

**Comment by nickit94** [comment]
> Здравствуйте!
> Спасибо за драйвер - это хорошая работа.
> Я заметил один баг: при обновлении экрана несколько крайних левых столбцов не обновляются.
> Я исправил это закомментировав следующее:
> OLED_SendCommand(0x00 /_| (oled_start_column & 0x0F)_/); // lo tetrad starting column address
> OLED_SendCommand(0x10 /_| (oled_start_column >> 4)_/); // hi tetrad starting column address
> Не знаю, насколько это правильно, но это работает.
> 
> Полный листинг функции с закоментированными строками:
> 
> void OLED_UpdateScreen()
> {
> for (uint8_t page_number = 0; page_number < 8; page_number++)
> {
> OLED_SendCommand(0x00 /_| (oled_start_column & 0x0F)_/); // lo tetrad starting column address
> OLED_SendCommand(0x10 /_| (oled_start_column >> 4)_/); // hi tetrad starting column address
> 
> ```
> 	OLED_SendCommand(0xB0 | page_number);					// starting address of the page
> 
> 	for (int16_t j = 0; j < OLED_WIDTH; j++)
> 	{
> 		OLED_SendData(oled_buffer[page_number * OLED_WIDTH + j]);
> 	}
> }
> ```
> 
> }

Спасибо за отзыв и замечание. Я писал эту библиотеку очень давно и могу ошибаться, но на разных драйверах для этого дисплея возникала потребность немного по-разному смещать столбцы. Как вариант можно попробовать поэксперементировать с **6**-ой строчкой в этом же файле:

`static uint8_t oled_start_column = 2;		// Display shift` 

Думаю, если установить значение в 0, то это должно исправить ситуацию, тогда не придется ничего комментировать.

**Comment by alexey496** [comment]
Да, Вы правы. Я изменил параметр
static uint8_t oled_start_column = 0;

И все стало хорошо. Наверное я должен был сам догадаться...
Спасибо

**Comment by nickit94** [comment]
> Да, Вы правы. Я изменил параметр
> static uint8_t oled_start_column = 0;
> 
> И все стало хорошо. Наверное я должен был сам догадаться...
> Спасибо

Рад был помочь и что библиотека оказалась полезна.
